// OxideXLA -- Integration Tests: JAX Code Generation
//
// These tests verify that the complete pipeline (parse -> IR -> codegen)
// produces valid-looking JAX Python code.

use std::path::PathBuf;
use oxide_xla::parser::load_onnx_model;
use oxide_xla::graph::IrGraph;
use oxide_xla::codegen::generate_jax_module;

fn fixture_path(name: &str) -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests");
    path.push("models");
    path.push(name);
    path
}

#[test]
fn codegen_linear_model() {
    let onnx = load_onnx_model(&fixture_path("linear.onnx")).unwrap();
    let ir = IrGraph::from_onnx(&onnx).unwrap();
    let code = generate_jax_module(&ir).unwrap();

    // Should contain the header.
    assert!(code.contains("Generated by OxideXLA"));

    // Should import jax.
    assert!(code.contains("import jax"));
    assert!(code.contains("import jax.numpy as jnp"));

    // Should have a forward function.
    assert!(code.contains("def forward(params,"));

    // Should reference jnp.matmul for the MatMul op.
    assert!(code.contains("jnp.matmul"));

    // Should reference jnp.add for the Add (bias) op.
    assert!(code.contains("jnp.add"));

    // Should have a return statement.
    assert!(code.contains("return"));

    // Should reference params dictionary.
    assert!(code.contains("params["));
}

#[test]
fn codegen_linear_relu_model() {
    let onnx = load_onnx_model(&fixture_path("linear_relu.onnx")).unwrap();
    let ir = IrGraph::from_onnx(&onnx).unwrap();
    let code = generate_jax_module(&ir).unwrap();

    // Should contain relu activation.
    assert!(code.contains("jax.nn.relu"));
}

#[test]
fn codegen_two_layer_mlp() {
    let onnx = load_onnx_model(&fixture_path("two_layer_mlp.onnx")).unwrap();
    let ir = IrGraph::from_onnx(&onnx).unwrap();
    let code = generate_jax_module(&ir).unwrap();

    // Should contain softmax.
    assert!(code.contains("jax.nn.softmax"));

    // Should have the jit decorator.
    assert!(code.contains("@jax.jit"));

    // Print for manual inspection during development.
    println!("--- Generated JAX code (two_layer_mlp) ---");
    println!("{}", code);
    println!("--- End ---");
}

#[test]
fn codegen_output_is_syntactically_complete() {
    // Verify the generated code has matching structure:
    // - starts with comments/imports
    // - has a function definition
    // - ends with a return

    let onnx = load_onnx_model(&fixture_path("linear.onnx")).unwrap();
    let ir = IrGraph::from_onnx(&onnx).unwrap();
    let code = generate_jax_module(&ir).unwrap();

    let lines: Vec<&str> = code.lines().collect();

    // First line should be the header comment.
    assert!(lines[0].starts_with("# Generated"));

    // Should have def forward somewhere.
    let has_def = lines.iter().any(|l| l.contains("def forward"));
    assert!(has_def, "Missing function definition");

    // Should have a return statement.
    let has_return = lines.iter().any(|l| l.trim().starts_with("return"));
    assert!(has_return, "Missing return statement");
}
