// OxideXLA -- Integration Tests: ONNX Parsing
//
// These tests verify that the parser correctly reads the fixture
// .onnx files generated by tests/generate_fixtures.py.

use std::path::PathBuf;
use oxide_xla::parser::load_onnx_model;

fn fixture_path(name: &str) -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests");
    path.push("models");
    path.push(name);
    path
}

#[test]
fn parse_linear_model() {
    let model = load_onnx_model(&fixture_path("linear.onnx"))
        .expect("Failed to parse linear.onnx");

    // Should have 2 computation nodes: MatMul and Add.
    assert_eq!(model.nodes.len(), 2, "Expected 2 nodes (MatMul, Add)");
    assert_eq!(model.nodes[0].op_type, "MatMul");
    assert_eq!(model.nodes[1].op_type, "Add");

    // Should have 2 initializers: weight [4,3] and bias [3].
    assert_eq!(model.initializers.len(), 2);
    assert!(model.initializers.contains_key("linear0.weight"));
    assert!(model.initializers.contains_key("linear0.bias"));

    let weight = &model.initializers["linear0.weight"];
    assert_eq!(weight.shape, vec![4, 3]);

    let bias = &model.initializers["linear0.bias"];
    assert_eq!(bias.shape, vec![3]);

    // Should have 1 data input (excluding initializers).
    assert_eq!(model.inputs.len(), 1);
    assert_eq!(model.inputs[0].0, "input");
    assert_eq!(model.inputs[0].1, vec![1, 4]);

    // Should have 1 output.
    assert_eq!(model.outputs.len(), 1);
    assert_eq!(model.outputs[0].0, "output");
}

#[test]
fn parse_linear_relu_model() {
    let model = load_onnx_model(&fixture_path("linear_relu.onnx"))
        .expect("Failed to parse linear_relu.onnx");

    // 3 nodes: MatMul, Add, Relu.
    assert_eq!(model.nodes.len(), 3);
    assert_eq!(model.nodes[0].op_type, "MatMul");
    assert_eq!(model.nodes[1].op_type, "Add");
    assert_eq!(model.nodes[2].op_type, "Relu");
}

#[test]
fn parse_two_layer_mlp() {
    let model = load_onnx_model(&fixture_path("two_layer_mlp.onnx"))
        .expect("Failed to parse two_layer_mlp.onnx");

    // 6 nodes: MatMul, Add, Relu, MatMul, Add, Softmax.
    assert_eq!(model.nodes.len(), 6);

    let op_types: Vec<&str> = model.nodes.iter().map(|n| n.op_type.as_str()).collect();
    assert_eq!(
        op_types,
        vec!["MatMul", "Add", "Relu", "MatMul", "Add", "Softmax"]
    );

    // 4 initializers: 2 weights + 2 biases.
    assert_eq!(model.initializers.len(), 4);
}

#[test]
fn parse_nonexistent_file_returns_error() {
    let result = load_onnx_model(&fixture_path("does_not_exist.onnx"));
    assert!(result.is_err());
}
