// OxideXLA -- JAX Module Generator
//
// This is the top-level code generation entry point. It takes a fully
// constructed IrGraph (with shapes inferred) and produces a complete
// Python module string.
//
// The generated code follows this structure:
//
//   1. Header comment and imports
//   2. forward(params, x) function with @jax.jit
//   3. Each IR node becomes one line of Python in the function body
//
// The output is a self-contained .py file that only depends on jax
// and jax.numpy. No Flax, no Equinox, no other frameworks.

use anyhow::Result;

use crate::graph::{IrGraph, IrNode, JaxOp};
use super::emit::emit_node;

/// Generate a complete JAX Python module from an IR graph.
pub fn generate_jax_module(ir_graph: &IrGraph) -> Result<String> {
    let mut lines: Vec<String> = Vec::new();

    // -- Header --
    lines.push("# Generated by OxideXLA".to_string());
    lines.push("# https://github.com/jeffasante/oxide-xla".to_string());
    lines.push("#".to_string());
    lines.push("# This file is auto-generated. Do not edit by hand.".to_string());
    lines.push(String::new());
    lines.push("import jax".to_string());
    lines.push("import jax.numpy as jnp".to_string());
    lines.push("import jax.lax".to_string());
    lines.push(String::new());
    lines.push(String::new());

    // -- Function signature --
    // Collect input names (the actual data inputs, not params).
    let input_names: Vec<String> = ir_graph
        .topo_order()
        .iter()
        .filter_map(|&idx| {
            let node = &ir_graph.graph[idx];
            match &node.op {
                JaxOp::Input => Some(node.name.clone()),
                _ => None,
            }
        })
        .collect();

    let input_args = input_names.join(", ");
    lines.push("@jax.jit".to_string());
    lines.push(format!("def forward(params, {}):", input_args));

    // -- Function body --
    // Walk the graph in topological order. Skip Input and Param nodes
    // (they are referenced directly by name). For each operation node,
    // emit one line of Python code.
    let mut has_operations = false;
    let mut last_output_name = String::new();

    for node_idx in ir_graph.topo_order() {
        let node = &ir_graph.graph[node_idx];

        match &node.op {
            JaxOp::Input | JaxOp::Param => continue,
            _ => {}
        }

        // Use ordered_inputs for correct operand ordering.
        let input_var_names: Vec<String> = node
            .ordered_inputs
            .iter()
            .map(|&idx| {
                let input_node = &ir_graph.graph[idx];
                var_name(input_node)
            })
            .collect();

        let output_var = var_name(node);
        let code_line = emit_node(node, &input_var_names, &output_var)?;

        lines.push(format!("    {}", code_line));
        last_output_name = output_var;
        has_operations = true;
    }

    // -- Return statement --
    if has_operations {
        lines.push(format!("    return {}", last_output_name));
    } else {
        // Edge case: model with no operations (just pass-through).
        if let Some(name) = input_names.first() {
            lines.push(format!("    return {}", name));
        }
    }

    lines.push(String::new());

    Ok(lines.join("\n"))
}

/// Convert an IrNode into the Python variable name used in the generated code.
///
/// Param nodes are referenced as params['key'], everything else uses
/// the sanitized node name directly.
fn var_name(node: &IrNode) -> String {
    match &node.op {
        JaxOp::Param => {
            format!("params['{}']", node.name)
        }
        JaxOp::Input => node.name.clone(),
        _ => node.name.clone(),
    }
}
